version: '2'
services:
  zookeeper:
    image: zookeeper:3.6
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
      - 9080:8080
  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    # build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-manage:
    image: kafkamanager/kafka-manager
    depends_on: 
      - kafka
    ports: 
      - 9100:9000
    environment: 
      ZK_HOSTS: host.docker.internal:2181